import * as T from 'three';
import {biomeOf} from './biomes.js';
export function aimTarget(origin,degrees,distance){const a=degrees*Math.PI/180;return{x:origin.x+Math.sin(a)*distance,z:origin.z+Math.cos(a)*distance};}
export function windDrift(settings){const speed=Math.max(0,Math.min(25,settings.wind||0)),a=(settings.windDirection||0)*Math.PI/180;return {x:Math.sin(a)*speed*.44704,z:Math.cos(a)*speed*.44704,count:speed===0?0:Math.min(76,Math.round(8+speed*2.7))};}
export function localWind(settings,rotation){const w=windDrift(settings),c=Math.cos(rotation),s=Math.sin(rotation);return [w.x*c-w.z*s,0,w.x*s+w.z*c];}
export function createShotEffects(view){
 const rng=()=>Math.random(),group=new T.Group(),wind=windDrift(view.world.settings),bio=biomeOf(view.world.settings.biome),dust=bio.dust,color=bio.spray;
 const positions=new Float32Array(76*3),g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(positions,3));g.setDrawRange(0,wind.count);const mat=new T.PointsMaterial({color,size:dust?.045:.07,transparent:true,opacity:.6,depthWrite:false});mat.onBeforeCompile=s=>s.fragmentShader=s.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nvec2 leaf=gl_PointCoord-vec2(.5);if(abs(leaf.x)*.65+abs(leaf.y)>.42)discard;');const debris=new T.Points(g,mat);debris.frustumCulled=false;group.add(debris);
 const seeds=Array.from({length:76},()=>({x:(rng()-.5)*42,y:(rng()-.5)*22,z:(rng()-.5)*42,phase:rng()*6.28}));let initialized=false;
 const burstGeo=new T.BufferGeometry();burstGeo.setAttribute('position',new T.BufferAttribute(new Float32Array(48*3),3));const burstMat=new T.PointsMaterial({color:'#b2c26d',size:.09,transparent:true,depthWrite:false}),burst=new T.Points(burstGeo,burstMat);burst.visible=false;burst.frustumCulled=false;group.add(burst);
 const ring=new T.Mesh(new T.RingGeometry(.8,1,48),new T.MeshBasicMaterial({color:'#fff2b7',transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.visible=false;group.add(ring);let particles=[],age=2,origin=null,putt=false;
 function hit(local,aim,lie,speed){const h=view.course,w=h.toWorld(local),a=(aim*Math.PI/180)+h.rotation;origin={x:w.x,y:h.height(local.x,local.z)+.04,z:w.z};putt=lie==='green';age=0;const count=putt?6:lie==='sand'?48:28;burstGeo.setDrawRange(0,count);burstMat.color.set(putt?'#fff4c5':lie==='sand'?view.world.bio.sand:lie==='rough'? '#839752':'#b1bc67');burstMat.size=putt?.025:lie==='sand'?.07:.09;particles=Array.from({length:count},()=>{const heading=a+(rng()-.5)*1.5,velocity=(putt?.15:1.4)+rng()*Math.min(4,speed*.08);return{vx:Math.sin(heading)*velocity,vz:Math.cos(heading)*velocity,vy:putt?.15:rng()*2.5+.8};});ring.position.set(origin.x,origin.y+.02,origin.z);ring.visible=burst.visible=true;}
 function update(dt,time){const camera=view.camera.position,a=g.attributes.position;for(let i=0;i<wind.count;i++){const seed=seeds[i];let x=initialized?a.getX(i):camera.x+seed.x,y=initialized?a.getY(i):camera.y+seed.y,z=initialized?a.getZ(i):camera.z+seed.z;x+=wind.x*dt*.8;z+=wind.z*dt*.8;y+=Math.sin(time*1.4+seed.phase)*dt*.1;for(const axis of ['x','y','z']){const half=axis==='y'?11:21;let v=axis==='x'?x:axis==='y'?y:z;v=camera[axis]+(((v-camera[axis]+half)%(half*2)+half*2)%(half*2))-half;if(axis==='x')x=v;else if(axis==='y')y=v;else z=v;}a.setXYZ(i,x,y,z);}initialized=true;a.needsUpdate=true;
  if(age<1){age+=dt;const p=burstGeo.attributes.position;particles.forEach((v,i)=>p.setXYZ(i,origin.x+v.vx*age,origin.y+Math.max(0,v.vy*age-4.9*age*age),origin.z+v.vz*age));p.needsUpdate=true;burstMat.opacity=Math.max(0,1-age/(putt?.3:.8));ring.scale.setScalar((putt?.12:.3)+age*(putt?.6:3));ring.material.opacity=Math.max(0,.5-age*1.6);if(age>.85)burst.visible=ring.visible=false;}
 }
 return {group,update,hit};
}
